package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	schemaV001, err := os.ReadFile("../../../schema/lockfile-v0.0.1.json")
	if err != nil {
		panic(err)
	}
	schemaV002, err := os.ReadFile("../../../schema/lockfile-v0.0.2.json")
	if err != nil {
		panic(err)
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package lockfile")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "const schemaV001 = %s\n\n", strconv.Quote(string(schemaV001)))
	fmt.Fprintf(&out, "const schemaV002 = %s\n", strconv.Quote(string(schemaV002)))

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("schema_gen.go", formatted, 0644); err != nil {
		panic(err)
	}
}
